/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.openhab.io.homekit.protocol.crypto;

import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.Signature;
import java.security.SignatureException;

import net.i2p.crypto.eddsa.EdDSAEngine;
import net.i2p.crypto.eddsa.EdDSAPrivateKey;
import net.i2p.crypto.eddsa.EdDSAPublicKey;
import net.i2p.crypto.eddsa.spec.EdDSANamedCurveTable;
import net.i2p.crypto.eddsa.spec.EdDSAParameterSpec;
import net.i2p.crypto.eddsa.spec.EdDSAPrivateKeySpec;
import net.i2p.crypto.eddsa.spec.EdDSAPublicKeySpec;

/**
 * Provides EdDSA (Edwards-curve Digital Signature Algorithm) signature generation for HomeKit protocol.
 *
 * This class implements digital signature generation using the Ed25519 curve with SHA-512 as specified
 * in the HomeKit Accessory Protocol (HAP). It is used to create digital signatures for messages
 * and data exchanged during the HomeKit pairing and communication process.
 *
 * Key features:
 * - Uses Ed25519 curve for efficient signature generation
 * - Implements SHA-512 for message hashing
 * - Manages both private and public key pairs
 * - Provides secure signature generation
 *
 * Security considerations:
 * - Uses cryptographically secure EdDSA implementation
 * - Implements proper key specification and parameter handling
 * - Maintains private key security
 * - Provides public key access for verification
 *
 * @author Karel Goderis - Initial contribution
 * @since 1.0
 */
public class HomekitEdsaSigner {

    /** The public key used for signature verification by other parties */
    private final EdDSAPublicKey publicKey;
    /** The private key used for signature generation */
    private final EdDSAPrivateKey privateKey;

    /**
     * Creates a new EdDSA signer with the specified private key.
     *
     * This constructor initializes the signer with an Ed25519 private key and derives the
     * corresponding public key. Both keys are stored for use in signature generation and
     * public key distribution.
     *
     * @param privateKeyBytes The raw private key bytes to use for signing
     * @throws IllegalArgumentException if the private key is invalid
     */
    public HomekitEdsaSigner(byte[] privateKeyBytes) {
        EdDSAParameterSpec spec = EdDSANamedCurveTable.getByName("ed25519-sha-512");
        EdDSAPrivateKeySpec privateKeySpec = new EdDSAPrivateKeySpec(privateKeyBytes, spec);
        EdDSAPublicKeySpec pubKeySpec = new EdDSAPublicKeySpec(privateKeySpec.getA(), spec);
        publicKey = new EdDSAPublicKey(pubKeySpec);
        privateKey = new EdDSAPrivateKey(privateKeySpec);
    }

    /**
     * Gets the public key associated with this signer.
     *
     * This method returns the raw bytes of the public key that can be used by other parties
     * to verify signatures generated by this signer.
     *
     * @return The raw public key bytes
     */
    public byte[] getPublicKey() {
        return publicKey.getAbyte();
    }

    /**
     * Generates a digital signature for the provided data.
     *
     * This method creates a digital signature using the private key held by this signer.
     * The signature process uses EdDSA with SHA-512 as specified in the HomeKit protocol.
     *
     * @param material The data to sign
     * @return The generated signature
     * @throws NoSuchAlgorithmException if SHA-512 is not available
     * @throws InvalidKeyException if the private key is invalid
     * @throws SignatureException if the signature generation fails
     */
    public byte[] sign(byte[] material) throws NoSuchAlgorithmException, InvalidKeyException, SignatureException {
        Signature sgr = new EdDSAEngine(MessageDigest.getInstance("SHA-512"));
        sgr.initSign(privateKey);
        sgr.update(material);
        return sgr.sign();
    }
}
