package org.openhab.io.homekit.internal.events;

import org.eclipse.jdt.annotation.NonNullByDefault;

@NonNullByDefault
public enum HomekitEventType {
    // --- Characteristic Events ---
    CHARACTERISTIC_VALUE_CHANGED,
    CHARACTERISTIC_ADDED,
    CHARACTERISTIC_REMOVED,
    CHARACTERISTIC_STATE_CHANGED,
    CHARACTERISTIC_UPDATED,
    CHARACTERISTIC_START_EVENTS,
    CHARACTERISTIC_STOP_EVENTS,

    // --- Service Events ---
    SERVICE_STATE_CHANGED,
    SERVICE_ADDED,
    SERVICE_REMOVED,

    // --- Accessory Events ---
    ACCESSORY_STATE_CHANGED,
    ACCESSORY_ADDED,
    ACCESSORY_REMOVED,

    // --- Server Events ---
    SERVER_STATE_CHANGED,
    SERVER_UPDATED,
    SERVER_STATE_DISCONNECTED,
    SERVER_STATE_CONNECTED,
    SERVER_STATE_PAIRED,
    SERVER_STATE_PAIR_VERIFIED,
    SERVER_STATE_MISSING_SETUP_CODE,
    SERVER_STATE_PAIRING_MISSING,
    SERVER_STATE_UNPAIRED,
    SERVER_STATE_PAIR_UNVERIFIED,
    SERVER_STATE_CONFIGURATION_NUMBER_CHANGED,

    // --- Pairing/Security Events ---
    PAIRING_STATE_CHANGED,
    SECURITY_VIOLATION
}
